# Generated by Django 4.2.15 on 2026-05-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_collection',
            field=models.BooleanField(default=False, verbose_name='Показывать в блоке "Коллекции" на главной'),
        ),
    ]
