# Generated by Django 4.2.15 on 2026-05-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_is_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Курьер по Минску (10 Br)'), ('pickup', 'Самовывоз (бесплатно)'), ('post', 'Почта Беларуси (от 5 Br)'), ('europost', 'Европочта (от 7 Br)')], default='courier', max_length=20, verbose_name='Способ доставки'),
        ),
    ]
