# Generated by Django 4.2.15 on 2026-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_stock_product_in_stock'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_sku_9aec58_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
